export const FETCH_FEED_REQUEST = "FETCH_FEED_REQUEST";
export const FETCH_FEED_SUCCESS = "FETCH_FEED_SUCCESS";
export const FETCH_FEED_FAIL = "FETCH_FEED_FAIL";
export const FETCH_FEED_RESET = "FETCH_FEED_RESET";

export const FETCH_EXPLORE_REQUEST = "FETCH_EXPLORE_REQUEST";
export const FETCH_EXPLORE_SUCCESS = "FETCH_EXPLORE_SUCCESS";
export const FETCH_EXPLORE_FAIL = "FETCH_EXPLORE_FAIL";
export const FETCH_EXPLORE_RESET = "FETCH_EXPLORE_RESET";

export const FETCH_PROFILE_REQUEST = "FETCH_PROFILE_REQUEST";
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
export const FETCH_PROFILE_FAIL = "FETCH_PROFILE_FAIL";

export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";

export const USER_SIGNOUT_REQUEST = "USER_SIGNOUT_REQUEST";
export const USER_SIGNOUT_SUCCESS = "USER_SIGNOUT_SUCCESS";
export const USER_SIGNOUT_FAIL = "USER_SIGNOUT_FAIL";

export const USER_FETCH_ME_REQUEST = "USER_FETCH_ME_REQUEST";
export const USER_FETCH_ME_SUCCESS = "USER_FETCH_ME_SUCCESS";
export const USER_FETCH_ME_FAIL = "USER_FETCH_ME_FAIL";

export const USER_FETCH_POSTS_REQUEST = "USER_FETCH_POSTS_REQUEST";
export const USER_FETCH_POSTS_SUCCESS = "USER_FETCH_POSTS_SUCCESS";
export const USER_FETCH_POSTS_FAIL = "USER_FETCH_POSTS_FAIL";
export const USER_FETCH_POSTS_RESET = "USER_FETCH_POSTS_RESET";

export const USER_PROFILE_UPDATE_REQUEST = "USER_PROFILE_UPDATE_REQUEST";
export const USER_PROFILE_UPDATE_SUCCESS = "USER_PROFILE_UPDATE_SUCCESS";
export const USER_PROFILE_UPDATE_FAIL = "USER_PROFILE_UPDATE_FAIL";
export const USER_PROFILE_UPDATE_RESET = "USER_PROFILE_UPDATE_RESET";

export const POST_CREATE_REQUEST = "POST_CREATE_REQUEST";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_FAIL = "POST_CREATE_FAIL";
export const POST_CREATE_RESET = "POST_CREATE_RESET";

export const POST_FETCH_REQUEST = "POST_FETCH_REQUEST";
export const POST_FETCH_SUCCESS = "POST_FETCH_SUCCESS";
export const POST_FETCH_FAIL = "POST_FETCH_FAIL";

export const POST_LIKE_REQUEST = "POST_LIKE_REQUEST";
export const POST_LIKE_SUCCESS = "POST_LIKE_SUCCESS";
export const POST_LIKE_FAIL = "POST_LIKE_FAIL";

export const POST_REBLOG_REQUEST = "POST_REBLOG_REQUEST";
export const POST_REBLOG_SUCCESS = "POST_REBLOG_SUCCESS";
export const POST_REBLOG_FAIL = "POST_REBLOG_FAIL";

export const POST_COMMENT_REQUEST = "POST_COMMENT_REQUEST";
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const POST_COMMENT_FAIL = "POST_COMMENT_FAIL";

export const POST_COMMENT_LIKE_REQUEST = "POST_COMMENT_LIKE_REQUEST";
export const POST_COMMENT_LIKE_SUCCESS = "POST_COMMENT_LIKE_SUCCESS";
export const POST_COMMENT_LIKE_FAIL = "POST_COMMENT_LIKE_FAIL";

export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAIL = "SEARCH_FAIL";
export const SEARCH_RESET = "SEARCH_RESET";

export const POST_FETCH_COMMENT_REQUEST = "POST_FETCH_COMMENT_REQUEST";
export const POST_FETCH_COMMENT_SUCCESS = "POST_FETCH_COMMENT_SUCCESS";
export const POST_FETCH_COMMENT_FAIL = "POST_FETCH_COMMENT_FAIL";
export const POST_COMMENT_RESET = "POST_COMMENT_RESET";

export const NOTIFICATION_FETCH_REQUEST = "NOTIFICATION_FETCH_REQUEST";
export const NOTIFICATION_FETCH_SUCCESS = "NOTIFICATION_FETCH_SUCCESS";
export const NOTIFICATION_FETCH_FAIL = "NOTIFICATION_FETCH_FAIL";
